apiVersion: 1

datasources:
  - name: InfluxDB-hivis
    uid: PA8DCAB329C51A876
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: hivis
      defaultBucket: hivis
      tlsSkipVerify: true
    secureJsonData:
      token: dad2bc0f8cd1fc00b3fd1d1e313c9d0984c77b258055de0f251ef903e6e89920
    isDefault: true
