apiVersion: 1

datasources:
  - name: InfluxDB-hivis
    uid: PA8DCAB329C51A876
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: hivis
      defaultBucket: hivis
      tlsSkipVerify: true
    secureJsonData:
      token: REPLACE_WITH_INFLUXDB_ADMIN_TOKEN  # see docs/credentials.md
    isDefault: true
